<?php
/**
 * @file
 * Output the markup for $build
 *
 * @ingroup bible_verses
 * @{
 */
$nav  = new $classes['navigation']();
$link = new $themes['link']();
?>
<!DOCTYPE html>
<html>
<head>
    <title><?php print $page_title ?></title>
    <link href="includes/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">
    <link href="custom.css" rel="stylesheet" type="text/css">
    <link
</head>

<body>
  <div id="navigation">
    <?php print $link->model($nav->getPrev())->attr(array(
      'class' => 'previous',
    ))->html();?>
    <?php print $link->model($nav->getNext())->attr(array(
      'class' => 'next',
    ))->html();?>
    <?php print $link->model($nav->getHome())->attr(array(
      'id' => 'home-link',
    ))->html(); ?>
  </div>

  <h1><?php print $page_title ?></h1>
<?php print $view->html();?>
</body>
</html>
